#!/bin/bash

if [ $# != 1 ]; then
    echo "Usage: new_version VERSION"
    exit
fi

version=$1
mkdir -p v$version
echo "Copying deploy package..."
cp -R deploy_package/* v${version}/
echo "Copying dev tree..."
cp -R ~/psu/capstone/src/fa2012cs487-teambanana/src/* v${version}/Visual_Training/
echo "Cleaning up..."
rm -rf v${version}/Visual_Training/web/img/.git
rm v${version}/Visual_Training/web/js/*.backup
sed -i '' "s/(\d)+\.(\d)+\.*(\d)*/${version}/" v${version}/Visual_Training/web/js/mainmenu.js
echo "2) Remember to test v${version}/index.html"
echo ""
echo "3) Then zip -r v${version}.zip v${version}"
